name: Build Caddy Image

on:
  workflow_dispatch:
  schedule:
    - cron: '18 9 * * 0'  # Weekly on Sundays at 9:18 AM UTC

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Note: Keep these versions in sync with Containerfile
  CADDY_VERSION: 2.11.3
  CLOUDFLARE_VERSION: 0.2.4
  IMAGE_TAG: 2.11.3-cf-0.2.4

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build container image
        id: build
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          containerfiles: |
            ./Containerfile

      - name: Log in to Container Registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        id: push
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
          create-storage-record: false

      - name: Sign the published OCI image
        if: ${{ github.event_name != 'pull_request' && env.COSIGN_PRIVATE_KEY != '' && env.COSIGN_PASSWORD != '' }}
        uses: samhclark/cosign-exec-action@v1.0.16
        env:
          COSIGN_PASSWORD: ${{ secrets.cosign_password }}
          COSIGN_PRIVATE_KEY: ${{ secrets.cosign_private_key }}
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            sign --yes --key=env://COSIGN_PRIVATE_KEY --new-bundle-format=false --use-signing-config=false
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}
